language: node_js
os: osx
osx_image: xcode12.5
node_js:
    - 14
before_script:
    - npm install -g @quasar/cli
install:
    - npm install
script:
    - quasar build -m electron
deploy:
    provider: releases
    api_key: ${GH_TOKEN}
    file_glob: true
    file:
        - "dist/electron/Packaged/*"
        - "dist/electron/Packaged/mac/*"
    skip_cleanup: true
    on:
        tags: true
